### PR TITLE
PlayerColor

### PR DESCRIPTION
**Pull request by Lazyprofile**
Players are able to choose their color before a custom match starts.

I am looking forward to see how you're going to built this project, and what it might turn into. I am not quite sure how you're going to program it, so I am not quite sure what to help with, but I want to help as much as I can.

### CODE REVIEW

**Comment by bellaPatricia** [comment]
Hi,

I'm not sure either. Most problematic thing for now is the new Patch which causes huge playerstruct issues. The whole structure is still in progress so I'm open for ideas. It will be mainly pure technical discussions if you like.

The existing Playerinterface is just a draft I though could be used for an actual implementation.
Feel free to deliver technical disuccion info (do you have a good plugin system or updater in mind? Maybe an application which can read memory out of x86_64 and x86 processes?). I look into that direction for now.
The actual implementation is meant to be as easy as possible.


About your PR: The problem is that you don't have all colors supported. I think there are 16 colors. The colorindex is stored as 1 byte in the playerstruct. You can map the index to a color 1 to 1. An actual transformation (Playercolor => Windows.Media.Color) is needed. I'd like to use the correct ARGB values for this.
So you need to create a class Playercolor with a transformation. I think an explicit cast is perfect for this. So you still know what happens when using it.
Implicit casting hides things which makes the thinking process in the later stage unneccesary complex.

**Comment by bellaPatricia** [comment]
If you want to take part in this thing from the beginning, we might want to find a tool for code quality and an easy introduction for potential others. I'll draw something this Sunday for it.

**Comment by Lazyprofile** [comment]
Never been much into SC2, but seems like it's time to reverse it. Thanks for the heads up about the colors. I am looking forward to see what you come up with this sunday.

**Comment by bellaPatricia** [comment]
I'm afraid I lied to you. I just returned but don't feel like doing a deep write up of things.
I don't even have Visio installed. 

I'm not sure what I exactly want. Something in the direction of micro services so I can replace modules more easily and maybe integrate them automatically.
I'm not sure how to build such a system. A proper plugin system might be one way.

**Pull request closed without merging**
